name: kotobati
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.14
  flutter_spinkit: ^5.2.0
  permission_handler: ^10.4.5
  file: ^7.0.0
  path_provider: ^2.1.1
  file_picker: ^5.5.0
  share_plus: ^7.0.2
  flutter_svg: ^2.0.7
  flutter_downloader: ^1.11.1
  flutter_local_notifications: ^15.1.1
  html: ^0.15.4
  shimmer: ^3.0.0
  cached_network_image: ^3.2.1
  flutter_pdfview: ^1.2.7
  screen_brightness: ^0.2.2
  #image_cropper: ^5.0.0
  croppy: ^1.1.0
  screenshot: ^2.1.0
  intl: ^0.18.0
  pdfx: ^2.4.0
  animated_text_kit: ^4.2.2
  uuid: ^3.0.7
  wave_linear_progress_indicator: ^0.1.0
  #custom_image_crop: ^0.0.10

  # State Management
  get: ^4.6.6
  #get: ^5.0.0-release-candidate-4

  # DB Store
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  mirai_responsive: any

  # Firebase
  firebase_core: ^2.15.0
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app_logo/icon.png"
  image_path_android: "assets/app_logo/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
