name: kotobati
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.4.0
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.11
  flutter_spinkit: ^5.2.0
  permission_handler: ^10.3.0
  file: ^6.1.4
  path_provider: ^2.0.15
  file_picker: ^5.3.2
  share_plus: ^7.0.2
  flutter_svg: ^2.0.7
  flutter_downloader: ^1.10.4
  html: ^0.15.4
  dio: ^5.2.1+1
  shimmer: ^2.0.0
  cached_network_image: ^3.2.1
  flutter_cached_pdfview: ^0.4.2

  # State Management
  get: ^4.6.5
  
  # DB Store
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  mirai_responsive: any

  # Firebase
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app_logo/icon.png"
  image_path_android: "assets/app_logo/icon.png"

flutter:

  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/

  fonts:
    - family: AlmaraiBold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf

    - family: AlmaraiRegular
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
