// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDduV7IBaw_cxCDj4A4keWiuvCzvcm2pjI',
    appId: '1:372770994138:web:f5526cf53dbec9eaffb2e3',
    messagingSenderId: '372770994138',
    projectId: 'kotobati-app',
    authDomain: 'kotobati-app.firebaseapp.com',
    storageBucket: 'kotobati-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5avEJMyXkesAnKQVKkur6yOFM86w0TA4',
    appId: '1:372770994138:android:09eff5077225f5e9ffb2e3',
    messagingSenderId: '372770994138',
    projectId: 'kotobati-app',
    storageBucket: 'kotobati-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrbYQGFQ4M0Efr4T0nWahZdsq7A0JMIJw',
    appId: '1:372770994138:ios:8db778b0a8c7729effb2e3',
    messagingSenderId: '372770994138',
    projectId: 'kotobati-app',
    storageBucket: 'kotobati-app.appspot.com',
    iosClientId: '372770994138-j345t6s695cjfbr0664b17cv74i3t8hb.apps.googleusercontent.com',
    iosBundleId: 'com.dghoughi.lahsen.kotobati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrbYQGFQ4M0Efr4T0nWahZdsq7A0JMIJw',
    appId: '1:372770994138:ios:24f2638f04df96a5ffb2e3',
    messagingSenderId: '372770994138',
    projectId: 'kotobati-app',
    storageBucket: 'kotobati-app.appspot.com',
    iosClientId: '372770994138-70nd3gu3r3po2s0jgo78uv2qsjfnhhs5.apps.googleusercontent.com',
    iosBundleId: 'com.dghoughi.lahsen.kotobati.kotobati.RunnerTests',
  );
}
